server:
  port: 9090
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: abc123
      driver-class-name: com.mysql.cj.jdbc.Driver